name: todo
description: "Noot."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2.4+28

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=1.17.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  async: ^2.8.2
  collection: ^1.17.0
  content_resolver: ^0.3.1
  crypto: ^3.0.2
  cupertino_icons: ^1.0.6
  highlight: ^0.7.0
  file_picker: ^8.1.6
#  flutter_code_editor: ^0.3.2
  flutter_code_editor:
#    path: ../../flutter-code-editor
    git:
      url: https://github.com/mlagerberg/flutter-code-editor.git
      ref: main
  flutter_donation_buttons: ^0.4.10
  flutter_file_dialog: ^3.0.2
  flutter_highlight: ^0.7.0
  intl: ^0.20.2
  package_info_plus: ^8.1.3
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  provider: ^6.1.2
  saf_util: ^0.6.1
  share_plus: ^10.1.3
  shared_preferences: ^2.3.4
  super_editor: ^0.3.0-dev.13
  super_editor_markdown: ^0.1.7
  url_launcher: ^6.3.1
  watcher: ^1.1.1
  webview_flutter: ^4.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Update splash using this command:
  # dart run flutter_native_splash:create --path=flutter_native_splash.yaml
  flutter_native_splash: ^2.4.3
  # dart run flutter_launcher_icons:generate -f flutter_launcher_icons.yaml
  flutter_launcher_icons: ^0.14.2

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See tat file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # for localizations
  generate: true

  assets:
    - assets/splash_icon.png
    - assets/icon.png
    - assets/editor.html
    - assets/codemirror/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Italic.ttf
          style: italic
        - asset: assets/fonts/Merriweather-Bold.ttf
          weight: 700
        - asset: assets/fonts/Merriweather-BoldItalic.ttf
          weight: 700
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
